<a href="https://colab.research.google.com/github/riinndescartes/Pemrograman-Lanjut-Python-DS23/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pengenalan Array**

Python tidak memiliki dukungan bawaan untuk Array, tetapi **Python List** dapat digunakan sebagai gantinya.

##**1. Susunan (List)**

Halaman ini menunjukkan cara menggunakan LISTS sebagai ARRAY, namun, untuk bekerja dengan array di Python kita harus mengimpor pustaka, seperti library `NumPy`.

Array digunakan untuk menyimpan beberapa nilai dalam satu variabel tunggal:

In [ ]:
cars = ["Ford", "Volvo", "BMW"]

print(cars)

['Ford', 'Volvo', 'BMW']


Jadi, apa itu Array?


Array adalah variabel khusus, yang dapat menampung lebih dari satu nilai pada satu waktu.

Jika Anda memiliki daftar item (daftar nama mobil, misalnya), menyimpan mobil dalam variabel tunggal dapat terlihat seperti ini:

car1 = "Ford"

car2 = "Volvo"

car3 = "BMW"


Namun, bagaimana jika Anda ingin menelusuri mobil-mobil tersebut dan menemukan satu mobil tertentu? Dan bagaimana jika Anda tidak memiliki 3 mobil, tetapi 300?

Solusinya adalah array!

Suatu array dapat menampung banyak nilai di bawah satu nama, dan Anda dapat mengakses nilai-nilai tersebut dengan merujuk ke nomor indeks.

##**2. Mengakses Elemen Array**


Anda merujuk pada elemen array dengan merujuk pada nomor indeks.

In [1]:
'''Contoh 1:
Dapatkan nilai item array pertama:'''

cars = ["Ford", "Volvo", "BMW"]
x = cars[0], [1]
print(x)

('Ford', [1])


In [ ]:
'''Contoh 2:
Ubah nilai item array pertama'''

cars = ["Ford", "Volvo", "BMW"]
cars[0] = "Toyota"
print(cars)

['Toyota', 'Volvo', 'BMW']


##**3. Panjang Sebuah Array**


Gunakan `len()`, metode ini untuk mengembalikan panjang suatu array (jumlah elemen dalam suatu array).

In [ ]:
'''Contoh 1:
Mengembalikan jumlah elemen
dalam cars array'''

cars = ["Ford", "Volvo", "BMW"]
x = len(cars)
print(x)

3


**Catatan:** Panjang suatu array selalu satu lebih panjang dari indeks array tertinggi.

##**4. Elemen Array Perulangan**

Anda dapat menggunakan `for i in loop` untuk mengulang semua elemen array.

In [ ]:
'''Contoh 1
Cetak setiap item dalam carsarray'''

cars = ["Ford", "Volvo", "BMW"]
for x in cars:
  print(x)

Ford
Volvo
BMW


##**5. Menambahkan Elemen Array**


Anda dapat menggunakan `append()`, metode ini untuk menambahkan elemen ke dalam array.

In [ ]:
'''Contoh 1
Tambahkan satu elemen lagi ke carsarray'''

cars = ["Ford", "Volvo", "BMW"]
cars.append("Honda")
print(cars)

['Ford', 'Volvo', 'BMW', 'Honda']


##**6. Menghapus Elemen Array**


Anda dapat menggunakan `pop()`, metode ini untuk menghapus elemen dari array.

In [ ]:
'''Contoh 1
Hapus elemen kedua dari carsarray'''

cars = ["Ford", "Volvo", "BMW"]

cars.pop(1)

print(cars)

['Ford', 'BMW']


Anda juga dapat menggunakan `remove()` metode ini untuk menghapus elemen dari array.

In [ ]:
'''Contoh 2
Hapus elemen yang memiliki nilai "Volvo":'''

cars = ["Ford", "Volvo", "BMW"]

cars.remove("Volvo")

print(cars)

['Ford', 'BMW']


**Catatan**: Metode daftar `remove()` hanya menghapus kemunculan pertama dari nilai yang ditentukan.

🎉**Array Method & Description**

- append(): Adds an element at the end of the list.

- clear(): Removes all the elements from the list.

- copy(): Returns a copy of the list.

- count(): Returns the number of elements with the specified value.

- extend(): Add the elements of a list (or any iterable), to the end of the current list.

- index(): Returns the index of the first element with the specified value.

- insert(): Adds an element at the specified position.

- pop(): Removes the element at the specified position.

- remove(): Removes the first item with the specified value.

- reverse(): Reverses the order of the list.

- sort(): Sorts the list.

##**8. Perbedaan List dan Array**

List

In [12]:
data_list = [1,2,3, "empat", 5.0]
print(data_list)

[1, 2, 3, 'empat', 5.0]


Array

In [13]:
import numpy as np

data_array = np.array([1,2,3,4,5])
print(data_array)

[1 2 3 4 5]


In [14]:
import numpy as np

data = np.loadtxt("/content/sample_data/california_housing_train.csv", delimiter = ',')
print(data)

FileNotFoundError: /content/sample_data/california_housing_train.csvt not found.

In [24]:
import numpy as np

# Change the delimiter to a single character, either space or semicolon
data = np.loadtxt("/content/BBRI2.csv", delimiter=',')  # Or delimiter=' ' if space-separated
print(data)

[[5600. 5600. 5425. 5425.]
 [5400. 5500. 5350. 5450.]
 [5475. 5475. 5350. 5400.]
 [5375. 5475. 5350. 5475.]
 [5425. 5450. 5375. 5425.]
 [5400. 5400. 5375. 5400.]
 [5400. 5550. 5400. 5550.]
 [5575. 5575. 5475. 5550.]
 [5475. 5525. 5450. 5525.]
 [5475. 5550. 5400. 5550.]
 [5500. 5525. 5450. 5525.]
 [5475. 5550. 5475. 5550.]
 [5500. 5575. 5500. 5575.]
 [5550. 5600. 5475. 5475.]
 [5425. 5475. 5400. 5400.]
 [5425. 5475. 5375. 5450.]
 [5450. 5500. 5425. 5425.]
 [5500. 5550. 5450. 5475.]
 [5500. 5500. 5425. 5450.]
 [5400. 5450. 5400. 5450.]
 [5450. 5475. 5400. 5425.]
 [5400. 5425. 5375. 5375.]
 [5425. 5500. 5400. 5400.]
 [5375. 5450. 5375. 5425.]
 [5450. 5475. 5425. 5450.]
 [5425. 5475. 5425. 5450.]
 [5450. 5525. 5425. 5525.]
 [5550. 5625. 5525. 5575.]
 [5625. 5700. 5600. 5625.]
 [5575. 5650. 5550. 5625.]
 [5600. 5625. 5575. 5625.]
 [5600. 5650. 5600. 5600.]
 [5625. 5700. 5625. 5650.]
 [5700. 5700. 5650. 5675.]
 [5675. 5750. 5650. 5650.]
 [5625. 5700. 5625. 5700.]
 [5700. 5700. 5650. 5650.]
 

In [17]:
import pandas as pd

df = pd.read_csv("/content/BBRI.JK.csv")
print(df)

           Date    Open    High     Low   Close    Adj Close     Volume
0    2023-06-05  5600.0  5600.0  5425.0  5425.0  5149.125000  255472600
1    2023-06-06  5400.0  5500.0  5350.0  5450.0  5172.854004   92019300
2    2023-06-07  5475.0  5475.0  5350.0  5400.0  5125.396484  150377000
3    2023-06-08  5375.0  5475.0  5350.0  5475.0  5196.582520   92794100
4    2023-06-09  5425.0  5450.0  5375.0  5425.0  5149.125000   77251000
..          ...     ...     ...     ...     ...          ...        ...
231  2024-05-29  4480.0  4500.0  4400.0  4410.0  4410.000000  465008500
232  2024-05-30  4400.0  4480.0  4310.0  4380.0  4380.000000  502927800
233  2024-05-31  4430.0  4470.0  4330.0  4340.0  4340.000000  655144100
234  2024-06-03  4430.0  4560.0  4400.0  4530.0  4530.000000  345770100
235  2024-06-04  4560.0  4590.0  4480.0  4490.0  4490.000000  144676700

[236 rows x 7 columns]


In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       236 non-null    object 
 1   Open       236 non-null    float64
 2   High       236 non-null    float64
 3   Low        236 non-null    float64
 4   Close      236 non-null    float64
 5   Adj Close  236 non-null    float64
 6   Volume     236 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.0+ KB
